/**
 * Emits registry/minima-palette.json — every Minima colour, resolved to hex,
 * for both modes.
 *
 * Some places cannot read a CSS variable: an email (clients strip them), an
 * Open Graph image (satori renders outside a browser), an SVG presentation
 * attribute, a native app, a chart library that wants a string. Before this,
 * every consumer that needed one re-parsed minima.css with regexes of its own
 * — three separate resolvers across two projects, each a copy of the cascade
 * that could drift from the real one. This is the one resolver, run where the
 * theme is built, shipped as the `palette` registry item.
 *
 * Read from the BUILT theme, so it is exactly what a consumer installs: the
 * light blocks for light (:root, :root:root), the dark blocks over them for
 * dark (.dark, :root:root.dark), every var() followed to a literal. Only
 * tokens that resolve to a colour are kept — sizes, curves and shadows are
 * not a palette — and every one that does is, so nothing is listed by hand.
 *
 *   node scripts/build-palette.mjs
 *
 * audit-palette fails if the committed JSON is not what this produces from the
 * committed theme.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { LAYOUT } from "./sources.mjs"
import { oklchToLinearSrgb } from "./generate-scales.mjs"

const root = new URL("../", import.meta.url)
export const THEME = new URL("registry/minima.css", root)
export const PALETTE = new URL("registry/minima-palette.json", root)

function collect(css, test) {
  const vars = {}
  for (const m of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
    const selector = m[1].trim().split("\n").pop().trim()
    if (!test(selector)) continue
    for (const d of m[2].matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) vars[d[1]] = d[2].trim()
  }
  return vars
}

const encode = (linear) => {
  const gamma = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055)
  return linear.map((c) => Math.round(Math.min(1, Math.max(0, gamma(c))) * 255))
}
const hex = (rgb, alpha = 1) =>
  "#" +
  [...rgb, ...(alpha < 1 ? [Math.round(alpha * 255)] : [])].map((n) => n.toString(16).padStart(2, "0")).join("")

/** A colour literal as hex, or null if the value is not a colour. */
export function toHex(value) {
  const alphaOf = (a) => (a === undefined ? 1 : a.endsWith("%") ? parseFloat(a) / 100 : parseFloat(a))
  let m = value.match(/^oklch\(\s*([\d.]+)(%?)\s+([\d.]+)\s+([\d.]+)?\s*(?:\/\s*([\d.]+%?))?\s*\)$/)
  if (m) {
    const L = m[2] ? Number(m[1]) / 100 : Number(m[1])
    return hex(encode(oklchToLinearSrgb(L, Number(m[3]), Number(m[4] ?? 0))), alphaOf(m[5]))
  }
  m = value.match(/^rgba?\(\s*([\d.]+)[\s,]+([\d.]+)[\s,]+([\d.]+)\s*(?:[/,]\s*([\d.]+%?))?\s*\)$/)
  if (m) return hex([m[1], m[2], m[3]].map((n) => Math.round(Number(n))), alphaOf(m[4]))
  m = value.match(/^#([0-9a-f]{6}|[0-9a-f]{8})$/i)
  if (m) return `#${m[1].toLowerCase()}`
  return null
}

/** The palette, from the text of the built theme. */
export function buildPalette(css) {
  const light = collect(css, (s) => /^(:root)+$/.test(s))
  const dark = { ...light, ...collect(css, (s) => /^(:root)*\.dark$/.test(s)) }

  const mode = (vars) => {
    const resolve = (name, seen = new Set()) => {
      if (seen.has(name) || vars[name] === undefined) return null
      seen.add(name)
      const v = vars[name]
      const ref = v.match(/^var\((--[\w-]+)(?:,\s*(.+))?\)$/)
      if (!ref) return v
      return resolve(ref[1], seen) ?? (ref[2] ? ref[2].trim() : null)
    }
    const out = {}
    for (const name of Object.keys(vars).sort()) {
      const literal = resolve(name)
      const h = literal && toHex(literal)
      if (h) out[name.slice(2)] = h
    }
    return out
  }

  return { light: mode(light), dark: mode(dark) }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (LAYOUT !== "registry") {
    console.log("build-palette runs in the registry — the lab has no built theme to read")
    process.exit(0)
  }
  const palette = buildPalette(readFileSync(THEME, "utf8"))
  writeFileSync(
    PALETTE,
    JSON.stringify(
      {
        $comment:
          "Generated by scripts/build-palette.mjs from registry/minima.css — do not edit. Every Minima colour as hex, for places that cannot read a CSS variable. Keys are the token names without the leading --.",
        ...palette,
      },
      null,
      2
    ) + "\n"
  )
  console.log(
    `wrote registry/minima-palette.json — ${Object.keys(palette.light).length} colours in light, ${Object.keys(palette.dark).length} in dark`
  )
}
