/**
 * Emits src/ramps.css — thirteen OKLCH ramps of twelve steps, for both modes.
 *
 * Carried over from minima-old, which is the one part of it worth carrying.
 * The ramps are generated on Radix step semantics rather than picked, so a
 * step number means the same thing in every hue: 3 is an element background,
 * 6 a subtle border, 9 the solid, 11 low-contrast text. That is what makes a
 * tinted icon tile expressible as "step 3 behind step 9" instead of two
 * colours somebody chose.
 *
 * Chroma is pushed past sRGB deliberately, so saturated steps render wide on
 * a P3 display and gamut-map down elsewhere.
 */
import { writeFileSync } from "node:fs"
import {
  rampVars,
  alphaVars,
  ALPHA_ROLES,
  SCRIM,
  HUES,
  STEPS,
} from "./generate-scales.mjs"

/* The step numbers are the scale; these names are the interface.
 *
 * A component that writes bg-amber-3 has hard-coded an ordinal, and renumbering
 * the scale — which we just did — silently changes what it means. A component
 * that writes bg-amber-fill says what it wants, and the mapping moves under it.
 * Numbers stay emitted because the ramp view and the generator need the
 * ordering; recipes should never touch them. */
const ROLE = {
  1: "bg",
  2: "bg-subtle",
  3: "fill",
  4: "fill-hover",
  5: "fill-active",
  6: "border",
  7: "border-strong",
  8: "solid",
  9: "text",
  10: "text-strong",
}

const block = (mode, selector) => {
  const vars = rampVars(mode)
  const alpha = alphaVars(mode)
  const names = ["gray", ...HUES.map((h) => h.name)]
  const lines = [`${selector} {`]
  for (const name of names) {
    lines.push(`  /* ${name} */`)
    for (const s of STEPS) lines.push(`  --${name}-${s}: ${vars[`${name}-${s}`]};`)
    for (const s of STEPS) {
      lines.push(`  --${name}-${ROLE[s]}: var(--${name}-${s});`)
    }
    for (const extra of ["on-solid", "mark", "on-mark", "reading"]) {
      if (vars[`${name}-${extra}`]) {
        lines.push(`  --${name}-${extra}: ${vars[`${name}-${extra}`]};`)
      }
    }
    /* The translucent rungs. Solved so each one reproduces its opaque twin
       over paper (light) or ink (dark) — see solveAlpha. */
    for (const role of Object.keys(ALPHA_ROLES)) {
      lines.push(`  --${name}-${role}: ${alpha[`${name}-${role}`]};`)
    }
  }
  lines.push(`  --scrim: rgb(0 0 0 / ${SCRIM[mode] * 100}%);`)
  lines.push("}")
  return lines.join("\n")
}

/* Expose every step as a Tailwind colour so a component can say bg-blue-3 /
   text-blue-11 rather than reaching for an arbitrary value. Step numbers do
   not collide with Tailwind's own 50-950 scale. */
const theme = () => {
  const names = ["gray", ...HUES.map((h) => h.name)]
  const lines = ["@theme inline {"]
  for (const name of names) {
    for (const s of STEPS) lines.push(`  --color-${name}-${s}: var(--${name}-${s});`)
    for (const s of STEPS) {
      lines.push(`  --color-${name}-${ROLE[s]}: var(--${name}-${ROLE[s]});`)
    }
    /* The computed text colour for step 9. Generated rather than chosen: the
       generator picks whichever of near-black or near-white clears the floor
       against that hue's solid, and throws if neither does. */
    lines.push(`  --color-${name}-on-solid: var(--${name}-on-solid);`)
    /* The mark and its text. Mode-dependent by design — see MARK_STEP. */
    lines.push(`  --color-${name}-mark: var(--${name}-mark);`)
    /* Gray alone gets a reading step — prose is neutral, and emitting one for
       every hue would be nine tokens nothing asks for. Guarded rather than
       emitted blind, which is the bug --color-gray-on-solid used to have. */
    if (name === "gray") lines.push(`  --color-gray-reading: var(--gray-reading);`)
    lines.push(`  --color-${name}-on-mark: var(--${name}-on-mark);`)
    /* Translucent rungs, named for the job rather than mirrored from the
       opaque role: `fill` replaces its ground, `tint` veils it. */
    for (const role of Object.keys(ALPHA_ROLES)) {
      lines.push(`  --color-${name}-${role}: var(--${name}-${role});`)
    }
  }
  lines.push("  --color-scrim: var(--scrim);")
  lines.push("}")
  return lines.join("\n")
}

const css = `/* Generated by scripts/build-ramps.mjs — do not edit. */

${block("light", ':root[data-theme="minima"]')}

${block("dark", ':root[data-theme="minima"].dark')}

${theme()}
`

writeFileSync(new URL("../src/ramps.css", import.meta.url), css)
const n = Object.keys(rampVars("light")).length + Object.keys(alphaVars("light")).length + 1
console.log(`wrote src/ramps.css — ${HUES.length + 1} ramps x ${STEPS.length} steps, ${n} vars per mode`)
